name              "alltherubies"
maintainer        "Ross Timson"
maintainer_email  "ross@rosstimson.com"
license           "Apache 2.0"
description       "Installs all-the-rubies via ruby_install cookbook"
long_description  "Install stable version of all rubies"
version           "0.1.0"
